### ISSUE TITLE
Create activities folder structure

### ISSUE THREAD

**Issue by amzoss** [visualizingthefuture/ethics-in-data-viz#2]
- activities
    - poverty maps
        - in person
            - separate printable version of both Mississippi maps
        - virtual
            - both maps on same Markdown file, probably side by side
    - Economist makeovers
        - in person
            - separate printable version of the "before" visualizations
        - virtual
            - separate folders for each "before" visualization, including a Markdown file with the visualization and maybe also the instructions

**Comment by amzoss** [comment]
All images embedded in slides: https://docs.google.com/presentation/d/1f2ZdlS4k28fqOWITB_dEi4DbABEAkjtpEkVIsG0k51Q/edit

**Comment by SPLOpenData** [comment]
Have a look again. Should be sorted now.
