### ISSUE TITLE
add icons for case studies, activities, etc.

### ISSUE THREAD

**Issue by amzoss** [visualizingthefuture/ethics-in-data-viz#5]
- case study icons on slides 12/14/16/18
- one icon for Census, a different for Economist
- another icon for discussion questions in lecture (5 & 25)

**Comment by amzoss** [comment]
Negeen will take a look at this

**Comment by negeenaghassi** [comment]
Added icons on 12/14/16/18 (case study), Census activity, Economist activity, 5/25 (discussion). Added icon references in slide notes where they first appeared and in references slide (currently slide 44).
