### ISSUE TITLE
add descriptions of activities to instructor guide

### ISSUE THREAD

**Issue by amzoss** [visualizingthefuture/ethics-in-data-viz#7]

**Comment by amzoss** [comment]
possibly include:
Tips for online vs. in-person instruction, small group vs. large group
Maybe a checklist for what to do beforehand (e.g., in-person: print out maps in advance)

**Comment by grynoch** [comment]
I took a first stab at this and added it to the readme file but not sure if this where we want them to live?

**Comment by grynoch** [comment]
Decided to move descriptions to readmes within each activity folder and will add text in main readme that points users to these descriptions
